# Generated by Django 3.2.10 on 2022-02-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='date_cerated',
            new_name='date_created',
        ),
    ]
