# Generated by Django 3.2.10 on 2022-02-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0004_userprofile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob',
            new_name='Date_of_Birth',
        ),
    ]
