# Generated by Django 3.2.10 on 2022-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0006_rename_date_of_birth_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Bio',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
